import type { ConversionSummary } from './types';

const n = (x: number) => x.toLocaleString('en-US');

/** Render the conversion summary as a plain-text report (saved only on the user's own machine). */
export function renderReport(s: ConversionSummary): string {
  const L: string[] = [];
  const h = (title: string) => {
    L.push('', title, '-'.repeat(title.length));
  };
  L.push('GED to Excel conversion report');
  L.push('==============================');

  h('Source');
  L.push(`File name: ${s.fileName}`);
  L.push(`Size: ${n(s.sizeBytes)} bytes`);
  L.push(`SHA-256: ${s.sha256}`);
  L.push(`Source program: ${s.sourceProgram || '(not stated)'}`);

  h('Detected format');
  L.push(`GEDCOM version: ${s.gedcomVersion || '(not stated)'}`);
  L.push(`Declared character set: ${s.declaredCharset || '(none)'}`);
  L.push(`Text encoding used: ${s.usedEncoding}`);
  L.push(`Total lines: ${n(s.totalLines)} (blank: ${n(s.blankLines)})`);

  h('Record counts');
  L.push(`People (INDI): ${n(s.people)}`);
  L.push(`Families (FAM): ${n(s.families)}`);
  L.push(`Other records: ${n(s.otherRecords)}`);
  for (const [tag, c] of Object.entries(s.otherRecordsByTag)) L.push(`  ${tag}: ${n(c)}`);

  h('Workbook rows');
  L.push(`People sheet: ${n(s.people)} rows`);
  L.push(`Facts sheet: ${n(s.factRows)} rows`);
  L.push(
    `Relationships sheet: ${n(s.relationshipRows)} rows (${n(s.familiesInRelationships)} families; ${n(s.placeholderRows)} placeholder rows for families with no links)`,
  );
  L.push(
    `Continuation columns: People ${s.maxParts.people}, Facts ${s.maxParts.facts}, Relationships ${s.maxParts.relationships} (largest number of All metadata / Raw GEDCOM parts)`,
  );
  L.push(`XML character substitutions (_xHHHH_): ${n(s.xmlSubstitutions)}`);
  L.push(`Display cells shortened to fit one cell (full text kept in continuation columns): ${n(s.shortenedDisplayCells)}`);

  h('Validation checks');
  for (const c of s.checks) L.push(`${c.status}  ${c.name}: ${c.detail}`);
  if (s.errors.length) {
    L.push('');
    L.push('Errors (the workbook was not created):');
    for (const e of s.errors) L.push(`  - ${e}`);
  }

  h('Unresolved references');
  if (s.unresolvedReferences.count === 0) L.push('None.');
  else {
    L.push(`${n(s.unresolvedReferences.count)} reference(s) to records that are not in the file (kept as written):`);
    for (const u of s.unresolvedReferences.list) L.push(`  line ${u.line}: ${u.tag} → ${u.target}`);
    if (s.unresolvedReferences.count > s.unresolvedReferences.list.length)
      L.push(`  … and ${n(s.unresolvedReferences.count - s.unresolvedReferences.list.length)} more`);
  }

  h('Duplicate IDs');
  L.push(s.duplicateIds.length === 0 ? 'None.' : `${s.duplicateIds.length} (all records kept): ${s.duplicateIds.join(', ')}`);

  h('Malformed lines');
  if (s.malformedLines.count === 0) L.push('None.');
  else {
    L.push(`${n(s.malformedLines.count)} line(s) kept as rows in the Facts sheet (Owner type "Malformed line"):`);
    for (const m of s.malformedLines.list) L.push(`  line ${m.line}: ${m.reason}: ${m.raw}`);
  }

  h('Warnings and limitations');
  if (s.warnings.length === 0) L.push('None.');
  for (const w of s.warnings) L.push(`- ${w}`);

  h('Workbook schema (short)');
  L.push('People: one row per person (INDI record), in file order.');
  L.push('Facts: every event/attribute of people and families, every other record (header, sources, notes, media, ...), and every malformed line.');
  L.push('Relationships: one row per spouse/child link of each family; families with no links get one placeholder row.');
  L.push('All metadata 1..N: lossless JSON of the row\'s GEDCOM lines; join the numbered columns in order to get the full text.');
  L.push('Raw GEDCOM 1..N: the original lines, joined with line breaks; join the numbered columns in order.');
  L.push('Connect rows using Person ID, Family ID, Owner ID and Owner type.');

  h('Generated');
  L.push(`Generated by: GED to Excel (runs entirely in your browser)`);
  L.push(`Generated at: ${s.generatedAt}`);
  L.push(
    `Stage timings (ms): ${Object.entries(s.durationsMs)
      .map(([k, v]) => `${k} ${Math.round(v)}`)
      .join(', ')}`,
  );
  return L.join('\n') + '\n';
}
